name: CI
on:
  push:
    branches: ["main"]

jobs:
  build:
    environment: main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Connect to Dockerhub
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:latest

  deployment: 
    needs: build
    environment: main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy to VPS
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.SERVER }}
          USER_NAME : ${{ secrets.SERVER_USERNAME  }}
        
        run: |
          echo "$PRIVATE_KEY" | base64 -d > private_key && chmod 600 private_key                                                                                                                             
            ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '

            whoami
            docker stop ${{ vars.CONTAINER_NAME }} || true && docker container rm ${{vars.CONTAINER_NAME}} || true && docker image rm -f tangguhriyadi/${{ vars.IMAGE_NAME }} || true
            docker pull tangguhriyadi/${{  vars.IMAGE_NAME  }}:latest
            docker run -d -p 3000:3000 --network paperclip_default --name ${{ vars.CONTAINER_NAME }} \
              -e DATABASE_HOST=${{ secrets.DATABASE_HOST }} \
              -e DATABASE_PORT=${{ secrets.DATABASE_PORT }} \
              -e DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} \
              -e DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} \
              -e DATABASE_NAME=${{ secrets.DATABASE_NAME }} \
              -e S3_ENDPOINT=${{ secrets.S3_ENDPOINT }} \
              -e S3_REGION=${{ secrets.S3_REGION }} \
              -e S3_ACCESS_KEY_ID=${{ secrets.S3_ACCESS_KEY_ID }} \
              -e S3_SECRET_ACCESS_KEY=${{ secrets.S3_SECRET_ACCESS_KEY }} \
              tangguhriyadi/${{ vars.IMAGE_NAME }}:latest
          '